services:
  - type: web
    name: email-classifier
    env: python
    plan: free
    region: ohio
    buildCommand: |
      # Frontend
      cd frontend && npm install && npm run build

      # Backend - instala direto na raiz
      pip install --upgrade pip
      pip install flask flask-cors python-dotenv google-genai PyPDF2 gunicorn
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        value: sua_chave_da_gemini_aqui
      - key: FLASK_ENV
        value: production
