services:
  - type: web
    name: email-classifier
    env: python
    plan: free
    region: ohio
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: sua_chave_da_google_aqui
      - key: FLASK_ENV
        value: production
    staticPublishPath: ./frontend/dist
