services:
  - type: web
    name: email-classifier
    env: python
    plan: free
    region: ohio
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        value: sua_chave_da_gemini_aqui
      - key: FLASK_ENV
        value: production
